<?php

/**
 * @file
 * Contains user_temp.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_temp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_temp module.
    case 'help.page.user_temp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Log temperature per user.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_temp_theme() {
  $theme = [];

  return $theme;
}
